server:
  port: 8097

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: ReviewService

data:
  mongodb:
    uri: mongodb://localhost:27017/library-db