server:
  port: 8096

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: CustomerService

data:
  mongodb:
    host: localhost
    port: 27017
    database: library-db


#  spring.data.mongodb.database=library-db
#  spring.data.mongodb.port=27017
#  spring.data.mongodb.host = localhost
