spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
      - id: customerModule
        uri: lb://CustomerService
        predicates:
        - Path=/customers/**
      - id: reviewModule
        uri: lb://ReviewService
        predicates:
          - Path=/books/**
      - id: bookQueryModule
        uri: lb://BookQueryService
        predicates:
          - Path=/books/new/**
      - id: bookCommandModule
        uri: lb://BookService
        predicates:
          - Path=/review/**

server:
  port: 8085



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

