
server:
  port: 8098

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: BookQueryService

  kafka:
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: "*"

data:
  mongodb:
    uri: mongodb://localhost:27017/library-db




